name: Merge check
on: [push, pull_request]
jobs:
  build:
    name: Merge check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.20
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: go build -v .
    - name: UT
      run: |
        bash scripts/ci/start_latest_sc.sh
        go test ./...